#!/usr/bin/env bash

set -eo pipefail

# Get the local version from Cargo.toml
package_name=$(awk '
  /^\[package\]/ { in_package=1 }
  /^\[/ && !/^\[package\]/ { in_package=0 }
  in_package && /^name = / { gsub(/"/, "", $3); print $3 }
' Cargo.toml)
local_version=$(jq -r .version package.json)
# Get the published version from cargo
published_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')

function semver { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

# Compare versions
if [ "$(semver $local_version)" -le "$(semver $published_version)" ]; then
  echo "Version $local_version is already published to cargo"
  exit 0
fi

cargo set-version $local_version

# Patch version numbers for local dependencies
local_deps=$(awk '
  /^\[dependencies\]/ { in_dependencies=1 }
  /^\[/ && !/^\[dependencies\]/ { in_dependencies=0 }
  in_dependencies && /path = "[^"]*"/ { print $1 }
' Cargo.toml)
if [ -n "$local_deps" ]; then
  for dep in $local_deps; do
    if [ "$dep" == "fusionamm-macros" ]; then
      latest_version=$(jq -r .version ../macros/package.json)
    else
      latest_version="$local_version"
    fi

    awk -v dep="$dep" -v version="$latest_version" '
      $1 == dep { sub(/path = "[^"]*"/, "version = \"" version "\"") } { print }
    ' Cargo.toml > tmp.toml && mv tmp.toml Cargo.toml
  done
fi

# Publish to cargo
echo "Publishing $package_name version $local_version to cargo"
cargo publish --allow-dirty || [ $? -eq 101 ]